language: c

os:
    - linux

compiler:
  - clang
  - gcc

notifications:
  email: change

env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - gcc --version
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("Jieba");Pkg.test("Jieba")'

