language: julia

os:
    - linux
    - osx

julia:
  - release
  - nightly

compiler:
  - clang

notifications:
  email: change

script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("Jieba");Pkg.test("Jieba")'

